package:
  name: test_upload_to_conda
  version:  "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - versioneer

  run:
    - python
    - pyyaml

about:
  home: https://github.com/Daniel-Ibarrola/TestUploadToConda
  license: MIT License
  summary: ""
  description: |
    This library provides some useful methods and classes to...
  dev_url: https://github.com/Daniel-Ibarrola/TestUploadToConda


